global using AutoMapper;
global using Microsoft.EntityFrameworkCore;
global using SampleMinimal.Core.Entities;
global using SampleMinimal.Core.Entities.DTO;
global using SampleMinimal.Core.Interfaces;
global using SampleMinimal.Core.Services;
global using SampleMinimal.Infra.DAL;
global using SampleMinimal.Infra.Repository;
global using Serilog;
